spring.application.name=ProductServiceJuly26
spring.datasource.url=jdbc:mysql://localhost:3306/productservicedb
spring.datasource.username=root
spring.datasource.password=Malay@7395

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
